[global]
disableWatchdogWarning = true

[server]
headless = true
port = 8501
enableCORS = false

[theme]
primaryColor = "#00d4ff"
backgroundColor = "#00172e"
secondaryBackgroundColor = "#002244"
textColor = "#ffffff"
font = "sans serif"
